#!/bin/bash

if [ ! -f /usr/local/bin/polipo ]; then
    ln -sf /bin/true /usr/local/bin/polipo
fi

if [ ! -f /usr/local/bin/hpts ]; then
    ln -sf /bin/true /usr/local/bin/hpts
fi

multitor --init "${TOR_INSTANCES}" --user debian-tor --socks-port "${MT_SOCKS_PORT}"  --control-port "${MT_CTRL_PORT}" --proxy privoxy --haproxy
/bin/bash
